### PR TITLE
use native file input handling

### PR DESCRIPTION
**Pull request by ross-spencer**
@prettybits this is rebased against the updated main. 

Not sure if this is temporary but it's not working on my local Firefox just now - I'm seeing the following on Firefox `106.0.2 ` on Ubuntu `22.04` what do you think?

```
13:37:28.167 Source map error: Error: request failed with status 404
Resource URL: https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.js
Source Map URL: pyodide.js.map
13:37:48.323 Python initialization complete [pyodide.asm.js:10:271183](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:48.324 [pyscript/pyodide] pyodide.loadPackage: micropip [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:37:48.325 [pyscript/pyodide] Loading micropip, pyparsing, packaging, distutils [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:37:48.344 Navigated to http://127.0.0.1:8001/
13:37:48.398 TypeError: NetworkError when attempting to fetch resource. [pyodide.asm.js:10:137379](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:48.400 TypeError: NetworkError when attempting to fetch resource. [pyodide.asm.js:10:137379](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:48.402 TypeError: NetworkError when attempting to fetch resource. [pyodide.asm.js:10:137379](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:48.403 TypeError: NetworkError when attempting to fetch resource. [pyodide.asm.js:10:137379](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:48.406 [pyscript/pyodide] Failed to load packaging, micropip, distutils, pyparsing [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:37:48.407 The following error occurred while loading packaging: [pyodide.asm.js:10:137718](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:48.407
TypeError: NetworkError when attempting to fetch resource. [pyodide.asm.js:10:137786](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:48.408 The following error occurred while loading micropip: [pyodide.asm.js:10:137718](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:48.408
TypeError: NetworkError when attempting to fetch resource. [pyodide.asm.js:10:137786](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:48.409 The following error occurred while loading distutils: [pyodide.asm.js:10:137718](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:48.409
TypeError: NetworkError when attempting to fetch resource. [pyodide.asm.js:10:137786](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:48.410 The following error occurred while loading pyparsing: [pyodide.asm.js:10:137718](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:48.410
TypeError: NetworkError when attempting to fetch resource. [pyodide.asm.js:10:137786](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:48.413 [pyscript/pyodide] importing pyscript.py [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:37:49.494
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 357, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 8, in <module>
ModuleNotFoundError: No module named 'micropip'
    PythonError https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js:10
    new_error https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js:10
    method_call_trampoline https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js:10
[pyodide.asm.js:10:149296](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:37:50.104 [py-config] config set from inline [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:37:50.107 [py-config] config set: 
Object { name: undefined, description: undefined, version: undefined, type: "app", author_name: undefined, author_email: undefined, license: undefined, schema_version: 1, autoclose_loader: true, runtimes: (1) […], … }
[logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:37:50.107 [py-config] Initializing runtimes [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:37:50.108 [pyscript/pyodide] Runtime config: 
Object { name: "pyodide-0.21.2", lang: "python", src: "https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.js" }
[logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:37:50.109 [pyscript/main] checking for py-config [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:37:50.109 [pyscript/main] add py-loader [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:37:50.178 [py-loader] Loading runtime... [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:37:50.179 [pyscript/pyodide] Loading pyodide [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:37:50.621 Source map error: Error: request failed with status 404
Resource URL: https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.js
Source Map URL: pyodide.js.map
13:38:17.075 Python initialization complete [pyodide.asm.js:10:271183](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.asm.js)
13:38:17.076 [pyscript/pyodide] pyodide.loadPackage: micropip [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:17.078 [pyscript/pyodide] Loading micropip, pyparsing, packaging, distutils [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:20.247 [pyscript/pyodide] Loaded micropip, packaging, pyparsing, distutils [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:20.249 [pyscript/pyodide] importing pyscript.py [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:28.584 [pyscript/pyodide] pyodide loaded and initialized [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:28.585 [py-loader] Runtime created... [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:28.586 [py-loader] Initializing components... [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:28.586 [py-script] py-mount: found 0 elements [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:28.592 [py-config] Loading env:  
Array [ "./demystify_digipres-3.0.0a1-py2.py3-none-any.whl" ]
[logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:28.593 [pyscript/pyodide] micropip install ./demystify_digipres-3.0.0a1-py2.py3-none-any.whl [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:29.171 [py-config] Paths to load:  
Array []
[logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:29.171 [py-config] All paths loaded [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:29.171 [py-loader] Initializing scripts... [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:29.172 [py-loader] Running post initializers... [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:29.173 [py-loader] Closing [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:29.173 [py-script] Initializing py-* event handlers... [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
13:38:29.175 [pyscript/runtime] PyScript page fully initialized [logger.ts:39:19](https://pyscript.net/releases/src/logger.ts)
```

Replaces: https://github.com/ross-spencer/demystify-lite/pull/11
Closes: https://github.com/ross-spencer/demystify-lite/pull/11

### CODE REVIEW

**Comment by prettybits** [comment]
Hm, still works fine when checking out your rebased branch on my end. Seems like a hopefully transient issue?
If not, does the network monitor in Firefox DevTools tell you anything more concrete than `NetworkError`?

Ideally there would at some point be a way to bundle PyScript together with precompiled Python package dependencies using standard tooling to be able to serve a package from the same (first-party) domain. Maybe this already exists or is actively being worked on? I might investigate this at some point.

**Comment by ross-spencer** [comment]
@prettybits what OS/browser versions are you working with?

**Comment by prettybits** [comment]
I'm on Arch Linux, with Firefox currently at version `106.0.3`. What's weird is that it looks like `pyodide.asm.js` was successfully loaded, but subsequent fetches from the same CDN fail?

**Comment by ross-spencer** [comment]
Closed via https://github.com/ross-spencer/demystify-lite/commit/603126f505b77746e22597ae2066652e2410749c

**Pull request closed without merging**
